train_vocab:
  dataset: "roneneldan/TinyStories"     # Required
  model_id: "TinyStories_4096"   # Required
  vocab_size: 4096           # Optional, defaults to 4096
  chunk_size: 512           # Optional, defaults to 512